{{- range .Values.jobs }}
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkSessionJob
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  deploymentName: {{ .deploymentName }}
  job:
    jarURI: {{ .jarURI | quote }}
    parallelism: {{ .parallelism }}
    upgradeMode: {{ .upgradeMode }}
    state: {{ .state }}
    args:
{{- range .args }}
      - {{ . | quote }}
{{- end }}
{{- end }}