apiVersion: v2
name: openreplay-databases
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.16.0"

dependencies:
  - name: clickhouse
    version: "0.1.0"
    repository: "file://charts/clickhouse"
    condition: clickhouse.enabled
  - name: kafka
    version: "11.8.6"
    repository: "file://charts/kafka"
    condition: kafka.enabled
  - name: minio
    version: "3.7.14"
    repository: "file://charts/minio"
    condition: minio.enabled
  - name: postgresql
    version: "9.8.2"
    repository: "file://charts/postgresql"
    condition: postgresql.enabled
  - name: redis
    version: "12.10.1"
    repository: "file://charts/redis"
    condition: redis.enabled
  - name: vault
    version: "0.22.1"
    repository: "file://charts/vault"
    condition: vault.enabled
